name: Deploy Hugo

on:
  push:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2  # v2 does not have submodules option now
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          # extended: true
      - run: ls
      # - run: hugo new site . --force
      - name: Build
        run: hugo --minify
      - run: ls
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.personal_token }}
        with:
          source-directory: './public'
          destination-github-username: 'charlie-captain'
          destination-repository-name: 'charlie-captain.github.io'
          user-email: chavezayne@gmail.com
          target-branch: main


